In [85]:
# Enable auto-reloading of modules
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [119]:
from nhl_scraper import scraper
!playwright install

scraper = scraper.Scraper()

Welcome to the NHL Scraper!

My name is Max and I'm the developer of this project and hockey fan. I hope you enjoy using this tool!

This is a work in progress and not all functionalities are available yet.

*** IMPORTANT ***

Make sure to run the following command in the terminal (it might take a while, but it will ensure that the playwright browser is installed):

$ playwright install
or
$ playwright install chromium

***

If you have any questions, please contact me on X: @woumaxx[https://x.com/woumaxx]

Thank you for using the NHL Scraper!

In [67]:
data = await scraper.scrape_toi(game_ids=[2024021043, 2024021044],)
data

Scraping NHL TOI Data:   0%|          | 0/2 [00:00<?, ?it/s]

Scraping NHL TOI Data: 100%|██████████| 2/2 [00:02<00:00,  1.21s/it]

{'TOI_combined': shape: (1_604, 14)
 ┌─────────┬──────┬──────────┬───────┬───┬───────────┬─────────────────────┬─────┬────────────┐
 │ Shift # ┆ Per  ┆ Duration ┆ Event ┆ … ┆ Duration  ┆ Team                ┆ H/V ┆ gameId     │
 │ ---     ┆ ---  ┆ ---      ┆ ---   ┆   ┆ (Seconds) ┆ ---                 ┆ --- ┆ ---        │
 │ i32     ┆ i32  ┆ str      ┆ str   ┆   ┆ ---       ┆ str                 ┆ str ┆ str        │
 │         ┆      ┆          ┆       ┆   ┆ i32       ┆                     ┆     ┆            │
 ╞═════════╪══════╪══════════╪═══════╪═══╪═══════════╪═════════════════════╪═════╪════════════╡
 │ 1       ┆ 1    ┆ 00:47    ┆       ┆ … ┆ 47        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 2       ┆ 1    ┆ 00:32    ┆       ┆ … ┆ 32        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 3       ┆ 1    ┆ 00:56    ┆       ┆ … ┆ 56        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 4       ┆ 1    ┆ 00:40    ┆       ┆ … ┆ 40        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 5       ┆ 1    ┆ 01:21    ┆       ┆ … ┆ 81        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ …       ┆ …    ┆ …        ┆ …     ┆ … ┆ …         ┆ …                   ┆ …   ┆ …          │
 │ 19      ┆ 3    ┆ 00:14    ┆ P     ┆ … ┆ 14        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 20      ┆ 3    ┆ 00:41    ┆       ┆ … ┆ 41        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 21      ┆ 3    ┆ 00:44    ┆       ┆ … ┆ 44        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 22      ┆ 3    ┆ 00:42    ┆       ┆ … ┆ 42        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 23      ┆ null ┆ 01:13    ┆       ┆ … ┆ 73        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 └─────────┴──────┴──────────┴───────┴───┴───────────┴─────────────────────┴─────┴────────────┘,
 'Summary_combined': shape: (251, 17)
 ┌──────┬─────┬───────┬───────┬───┬──────────────────┬─────────────────────┬─────┬────────────┐
 │ Per  ┆ SHF ┆ AVG   ┆ TOI   ┆ … ┆ SH TOT (Seconds) ┆ Team                ┆ H/V ┆ gameId     │
 │ ---  ┆ --- ┆ ---   ┆ ---   ┆   ┆ ---              ┆ ---                 ┆ --- ┆ ---        │
 │ i32  ┆ i32 ┆ str   ┆ str   ┆   ┆ i32              ┆ str                 ┆ str ┆ str        │
 ╞══════╪═════╪═══════╪═══════╪═══╪══════════════════╪═════════════════════╪═════╪════════════╡
 │ 1    ┆ 8   ┆ 00:42 ┆ 05:43 ┆ … ┆ 0                ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 2    ┆ 7   ┆ 01:01 ┆ 07:12 ┆ … ┆ 0                ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 3    ┆ 7   ┆ 00:51 ┆ 05:58 ┆ … ┆ 0                ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 1    ┆ 7   ┆ 01:08 ┆ 08:01 ┆ … ┆ 0                ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 2    ┆ 9   ┆ 00:44 ┆ 06:38 ┆ … ┆ 0                ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ …    ┆ …   ┆ …     ┆ …     ┆ … ┆ …                ┆ …                   ┆ …   ┆ …          │
 │ null ┆ 1   ┆ 00:46 ┆ 00:46 ┆ … ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 1    ┆ 7   ┆ 00:47 ┆ 05:31 ┆ … ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 2    ┆ 7   ┆ 01:00 ┆ 07:01 ┆ … ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 3    ┆ 8   ┆ 00:44 ┆ 05:53 ┆ … ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ null ┆ 1   ┆ 01:13 ┆ 01:13 ┆ … ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 └──────┴─────┴───────┴───────┴───┴──────────────────┴─────────────────────┴─────┴────────────┘,
 'game_details': {'2024021044': {'GameId': '2024021044',
   'FirstYear': '2024',
   'SecondYear': '2025',
   'ShortId': '021044',
   'season': '2024-2025',
   'Away': 'ST. LOUIS BLUES',
   'Home': 'PITTSBURGH PENGUINS',
   'homeTOI': shape: (384, 13)
   ┌─────────┬─────┬──────────┬───────┬───┬────────────────────────┬───────────┬────────────┬─────┐
   │ Shift # ┆ Per ┆ Duration ┆ Event ┆ … ┆ End Game Time - Legacy ┆ Duration  ┆ Team       ┆ H/V │
   │ ---     ┆ --- ┆ ---      ┆ ---   ┆   ┆ ---                    ┆ (Seconds) ┆ ---        ┆ --- │
   │ i32     ┆ i32 ┆ str      ┆ str   ┆   ┆ str                    ┆ ---       ┆ str        ┆ str │
   │         ┆     ┆          ┆       ┆   ┆                        ┆ i32       ┆            ┆     │
   ╞═════════╪═════╪══════════╪═══════╪═══╪════════════════════════╪═══════════╪════════════╪═════╡
   │ 1       ┆ 1   ┆ 00:46    ┆       ┆ … ┆ 16:57                  ┆ 46        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 2       ┆ 1   ┆ 00:46    ┆       ┆ … ┆ 12:48                  ┆ 46        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 3       ┆ 1   ┆ 00:41    ┆       ┆ … ┆ 5:11                   ┆ 41        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 4       ┆ 1   ┆ 00:17    ┆       ┆ … ┆ 2:24                   ┆ 17        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 5       ┆ 2   ┆ 00:36    ┆       ┆ … ┆ 17:04                  ┆ 36        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ …       ┆ …   ┆ …        ┆ …     ┆ … ┆ …                      ┆ …         ┆ …          ┆ …   │
   │ 19      ┆ 3   ┆ 00:43    ┆       ┆ … ┆ 8:46                   ┆ 43        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 20      ┆ 3   ┆ 00:21    ┆       ┆ … ┆ 7:55                   ┆ 21        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 21      ┆ 3   ┆ 00:56    ┆       ┆ … ┆ 6:13                   ┆ 56        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 22      ┆ 3   ┆ 00:58    ┆       ┆ … ┆ 3:57                   ┆ 58        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 23      ┆ 3   ┆ 00:55    ┆ G     ┆ … ┆ 0:08                   ┆ 55        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   └─────────┴─────┴──────────┴───────┴───┴────────────────────────┴───────────┴────────────┴─────┘,
   'awayTOI': shape: (396, 13)
   ┌─────────┬─────┬──────────┬───────┬───┬─────────────────┬───────────┬─────────────────┬─────┐
   │ Shift # ┆ Per ┆ Duration ┆ Event ┆ … ┆ End Game Time - ┆ Duration  ┆ Team            ┆ H/V │
   │ ---     ┆ --- ┆ ---      ┆ ---   ┆   ┆ Legacy          ┆ (Seconds) ┆ ---             ┆ --- │
   │ i32     ┆ i32 ┆ str      ┆ str   ┆   ┆ ---             ┆ ---       ┆ str             ┆ str │
   │         ┆     ┆          ┆       ┆   ┆ str             ┆ i32       ┆                 ┆     │
   ╞═════════╪═════╪══════════╪═══════╪═══╪═════════════════╪═══════════╪═════════════════╪═════╡
   │ 1       ┆ 1   ┆ 00:47    ┆       ┆ … ┆ 18:19           ┆ 47        ┆ ST. LOUIS BLUES ┆ V   │
   │ 2       ┆ 1   ┆ 00:32    ┆       ┆ … ┆ 17:11           ┆ 32        ┆ ST. LOUIS BLUES ┆ V   │
   │ 3       ┆ 1   ┆ 00:56    ┆       ┆ … ┆ 13:35           ┆ 56        ┆ ST. LOUIS BLUES ┆ V   │
   │ 4       ┆ 1   ┆ 00:40    ┆       ┆ … ┆ 11:17           ┆ 40        ┆ ST. LOUIS BLUES ┆ V   │
   │ 5       ┆ 1   ┆ 01:21    ┆       ┆ … ┆ 7:06            ┆ 81        ┆ ST. LOUIS BLUES ┆ V   │
   │ …       ┆ …   ┆ …        ┆ …     ┆ … ┆ …               ┆ …         ┆ …               ┆ …   │
   │ 22      ┆ 3   ┆ 00:50    ┆       ┆ … ┆ 9:27            ┆ 50        ┆ ST. LOUIS BLUES ┆ V   │
   │ 23      ┆ 3   ┆ 01:08    ┆       ┆ … ┆ 7:08            ┆ 68        ┆ ST. LOUIS BLUES ┆ V   │
   │ 24      ┆ 3   ┆ 00:39    ┆       ┆ … ┆ 4:51            ┆ 39        ┆ ST. LOUIS BLUES ┆ V   │
   │ 25      ┆ 3   ┆ 02:13    ┆       ┆ … ┆ 0:56            ┆ 133       ┆ ST. LOUIS BLUES ┆ V   │
   │ 26      ┆ 3   ┆ 00:15    ┆ G     ┆ … ┆ 0:08            ┆ 15        ┆ ST. LOUIS BLUES ┆ V   │
   └─────────┴─────┴──────────┴───────┴───┴─────────────────┴───────────┴─────────────────┴─────┘,
   'homeSummary': shape: (57, 16)
   ┌─────┬─────┬───────┬───────┬───┬──────────────────┬──────────────────┬─────────────────────┬─────┐
   │ Per ┆ SHF ┆ AVG   ┆ TOI   ┆ … ┆ PP TOT (Seconds) ┆ SH TOT (Seconds) ┆ Team                ┆ H/V │
   │ --- ┆ --- ┆ ---   ┆ ---   ┆   ┆ ---              ┆ ---              ┆ ---                 ┆ --- │
   │ i32 ┆ i32 ┆ str   ┆ str   ┆   ┆ i32              ┆ i32              ┆ str                 ┆ str │
   ╞═════╪═════╪═══════╪═══════╪═══╪══════════════════╪══════════════════╪═════════════════════╪═════╡
   │ 1   ┆ 4   ┆ 00:37 ┆ 02:30 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 2   ┆ 5   ┆ 00:39 ┆ 03:17 ┆ … ┆ 0                ┆ 28               ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 3   ┆ 2   ┆ 00:43 ┆ 01:27 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 1   ┆ 4   ┆ 00:44 ┆ 02:58 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 2   ┆ 5   ┆ 00:45 ┆ 03:47 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ …   ┆ …   ┆ …     ┆ …     ┆ … ┆ …                ┆ …                ┆ …                   ┆ …   │
   │ 2   ┆ 7   ┆ 00:57 ┆ 06:40 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 3   ┆ 6   ┆ 00:48 ┆ 04:51 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 1   ┆ 7   ┆ 00:55 ┆ 06:28 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 2   ┆ 8   ┆ 00:41 ┆ 05:34 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 3   ┆ 8   ┆ 00:47 ┆ 06:23 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   └─────┴─────┴───────┴───────┴───┴──────────────────┴──────────────────┴─────────────────────┴─────┘,
   'awaySummary': shape: (58, 16)
   ┌─────┬─────┬───────┬───────┬───┬──────────────────┬──────────────────┬─────────────────┬─────┐
   │ Per ┆ SHF ┆ AVG   ┆ TOI   ┆ … ┆ PP TOT (Seconds) ┆ SH TOT (Seconds) ┆ Team            ┆ H/V │
   │ --- ┆ --- ┆ ---   ┆ ---   ┆   ┆ ---              ┆ ---              ┆ ---             ┆ --- │
   │ i32 ┆ i32 ┆ str   ┆ str   ┆   ┆ i32              ┆ i32              ┆ str             ┆ str │
   ╞═════╪═════╪═══════╪═══════╪═══╪══════════════════╪══════════════════╪═════════════════╪═════╡
   │ 1   ┆ 8   ┆ 00:42 ┆ 05:43 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 2   ┆ 7   ┆ 01:01 ┆ 07:12 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 3   ┆ 7   ┆ 00:51 ┆ 05:58 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 1   ┆ 7   ┆ 01:08 ┆ 08:01 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 2   ┆ 9   ┆ 00:44 ┆ 06:38 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ …   ┆ …   ┆ …     ┆ …     ┆ … ┆ …                ┆ …                ┆ …               ┆ …   │
   │ 2   ┆ 8   ┆ 00:44 ┆ 05:56 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 3   ┆ 8   ┆ 00:47 ┆ 06:19 ┆ … ┆ 45               ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 1   ┆ 7   ┆ 00:50 ┆ 05:51 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 2   ┆ 10  ┆ 00:41 ┆ 06:50 ┆ … ┆ 36               ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 3   ┆ 9   ┆ 00:54 ┆ 08:11 ┆ … ┆ 41               ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   └─────┴─────┴───────┴───────┴───┴──────────────────┴──────────────────┴─────────────────┴─────┘},
  '2024021043': {'GameId': '2024021043',
   'FirstYear': '2024',
   'SecondYear': '2025',
   'ShortId': '021043',
   'season': '2024-2025',
   'Away': 'TAMPA BAY LIGHTNING',
   'Home': 'PHILADELPHIA FLYERS',
   'homeTOI': shape: (412, 13)
   ┌─────────┬──────┬──────────┬───────┬───┬─────────────────────────┬───────────┬──────────────┬─────┐
   │ Shift # ┆ Per  ┆ Duration ┆ Event ┆ … ┆ End Game Time - Legacy  ┆ Duration  ┆ Team         ┆ H/V │
   │ ---     ┆ ---  ┆ ---      ┆ ---   ┆   ┆ ---                     ┆ (Seconds) ┆ ---          ┆ --- │
   │ i32     ┆ i32  ┆ str      ┆ str   ┆   ┆ str                     ┆ ---       ┆ str          ┆ str │
   │         ┆      ┆          ┆       ┆   ┆                         ┆ i32       ┆              ┆     │
   ╞═════════╪══════╪══════════╪═══════╪═══╪═════════════════════════╪═══════════╪══════════════╪═════╡
   │ 1       ┆ 1    ┆ 00:39    ┆       ┆ … ┆ 18:26                   ┆ 39        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 2       ┆ 1    ┆ 01:02    ┆       ┆ … ┆ 15:14                   ┆ 62        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 3       ┆ 1    ┆ 00:36    ┆ P     ┆ … ┆ 13:13                   ┆ 36        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 4       ┆ 1    ┆ 00:42    ┆       ┆ … ┆ 11:48                   ┆ 42        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 5       ┆ 1    ┆ 01:09    ┆       ┆ … ┆ 9:52                    ┆ 69        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ …       ┆ …    ┆ …        ┆ …     ┆ … ┆ …                       ┆ …         ┆ …            ┆ …   │
   │ 19      ┆ 3    ┆ 00:14    ┆ P     ┆ … ┆ 9:06                    ┆ 14        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 20      ┆ 3    ┆ 00:41    ┆       ┆ … ┆ 6:16                    ┆ 41        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 21      ┆ 3    ┆ 00:44    ┆       ┆ … ┆ 3:12                    ┆ 44        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 22      ┆ 3    ┆ 00:42    ┆       ┆ … ┆ 1:04                    ┆ 42        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 23      ┆ null ┆ 01:13    ┆       ┆ … ┆ 0:00                    ┆ 73        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   └─────────┴──────┴──────────┴───────┴───┴─────────────────────────┴───────────┴──────────────┴─────┘,
   'awayTOI': shape: (412, 13)
   ┌─────────┬──────┬──────────┬───────┬───┬────────────────────────┬───────────┬───────────┬─────┐
   │ Shift # ┆ Per  ┆ Duration ┆ Event ┆ … ┆ End Game Time - Legacy ┆ Duration  ┆ Team      ┆ H/V │
   │ ---     ┆ ---  ┆ ---      ┆ ---   ┆   ┆ ---                    ┆ (Seconds) ┆ ---       ┆ --- │
   │ i32     ┆ i32  ┆ str      ┆ str   ┆   ┆ str                    ┆ ---       ┆ str       ┆ str │
   │         ┆      ┆          ┆       ┆   ┆                        ┆ i32       ┆           ┆     │
   ╞═════════╪══════╪══════════╪═══════╪═══╪════════════════════════╪═══════════╪═══════════╪═════╡
   │ 1       ┆ 1    ┆ 00:08    ┆       ┆ … ┆ 18:06                  ┆ 8         ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 2       ┆ 1    ┆ 01:05    ┆       ┆ … ┆ 16:13                  ┆ 65        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 3       ┆ 1    ┆ 00:23    ┆ P     ┆ … ┆ 13:13                  ┆ 23        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 4       ┆ 1    ┆ 01:00    ┆       ┆ … ┆ 8:51                   ┆ 60        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 5       ┆ 1    ┆ 00:23    ┆       ┆ … ┆ 8:00                   ┆ 23        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ …       ┆ …    ┆ …        ┆ …     ┆ … ┆ …                      ┆ …         ┆ …         ┆ …   │
   │ 15      ┆ 3    ┆ 01:03    ┆       ┆ … ┆ 13:06                  ┆ 63        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 16      ┆ 3    ┆ 00:11    ┆       ┆ … ┆ 11:11                  ┆ 11        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 17      ┆ 3    ┆ 00:38    ┆       ┆ … ┆ 5:08                   ┆ 38        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 18      ┆ 3    ┆ 00:40    ┆       ┆ … ┆ 2:32                   ┆ 40        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 19      ┆ null ┆ 00:44    ┆       ┆ … ┆ 1:55                   ┆ 44        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   └─────────┴──────┴──────────┴───────┴───┴────────────────────────┴───────────┴───────────┴─────┘,
   'homeSummary': shape: (68, 16)
   ┌──────┬─────┬───────┬───────┬───┬──────────────────┬──────────────────┬─────────────────────┬─────┐
   │ Per  ┆ SHF ┆ AVG   ┆ TOI   ┆ … ┆ PP TOT (Seconds) ┆ SH TOT (Seconds) ┆ Team                ┆ H/V │
   │ ---  ┆ --- ┆ ---   ┆ ---   ┆   ┆ ---              ┆ ---              ┆ ---                 ┆ --- │
   │ i32  ┆ i32 ┆ str   ┆ str   ┆   ┆ i32              ┆ i32              ┆ str                 ┆ str │
   ╞══════╪═════╪═══════╪═══════╪═══╪══════════════════╪══════════════════╪═════════════════════╪═════╡
   │ 1    ┆ 9   ┆ 00:47 ┆ 07:06 ┆ … ┆ 0                ┆ 42               ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 2    ┆ 6   ┆ 00:53 ┆ 05:21 ┆ … ┆ 0                ┆ 39               ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 3    ┆ 7   ┆ 00:39 ┆ 04:36 ┆ … ┆ 0                ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 1    ┆ 10  ┆ 00:49 ┆ 08:15 ┆ … ┆ 0                ┆ 58               ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 2    ┆ 9   ┆ 01:08 ┆ 10:12 ┆ … ┆ 56               ┆ 196              ┆ PHILADELPHIA FLYERS ┆ H   │
   │ …    ┆ …   ┆ …     ┆ …     ┆ … ┆ …                ┆ …                ┆ …                   ┆ …   │
   │ null ┆ 1   ┆ 00:46 ┆ 00:46 ┆ … ┆ 0                ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 1    ┆ 7   ┆ 00:47 ┆ 05:31 ┆ … ┆ 0                ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 2    ┆ 7   ┆ 01:00 ┆ 07:01 ┆ … ┆ 36               ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 3    ┆ 8   ┆ 00:44 ┆ 05:53 ┆ … ┆ 0                ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   │
   │ null ┆ 1   ┆ 01:13 ┆ 01:13 ┆ … ┆ 0                ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   │
   └──────┴─────┴───────┴───────┴───┴──────────────────┴──────────────────┴─────────────────────┴─────┘,
   'awaySummary': shape: (68, 16)
   ┌──────┬─────┬───────┬───────┬───┬──────────────────┬──────────────────┬─────────────────────┬─────┐
   │ Per  ┆ SHF ┆ AVG   ┆ TOI   ┆ … ┆ PP TOT (Seconds) ┆ SH TOT (Seconds) ┆ Team                ┆ H/V │
   │ ---  ┆ --- ┆ ---   ┆ ---   ┆   ┆ ---              ┆ ---              ┆ ---                 ┆ --- │

In [68]:
data['TOI_combined']

shape: (1_604, 14)
┌─────────┬──────┬──────────┬───────┬───┬───────────┬─────────────────────┬─────┬────────────┐
│ Shift # ┆ Per  ┆ Duration ┆ Event ┆ … ┆ Duration  ┆ Team                ┆ H/V ┆ gameId     │
│ ---     ┆ ---  ┆ ---      ┆ ---   ┆   ┆ (Seconds) ┆ ---                 ┆ --- ┆ ---        │
│ i32     ┆ i32  ┆ str      ┆ str   ┆   ┆ ---       ┆ str                 ┆ str ┆ str        │
│         ┆      ┆          ┆       ┆   ┆ i32       ┆                     ┆     ┆            │
╞═════════╪══════╪══════════╪═══════╪═══╪═══════════╪═════════════════════╪═════╪════════════╡
│ 1       ┆ 1    ┆ 00:47    ┆       ┆ … ┆ 47        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
│ 2       ┆ 1    ┆ 00:32    ┆       ┆ … ┆ 32        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
│ 3       ┆ 1    ┆ 00:56    ┆       ┆ … ┆ 56        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
│ 4       ┆ 1    ┆ 00:40    ┆       ┆ … ┆ 40        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
│ 5       ┆ 1    ┆ 01:21    ┆       ┆ … ┆ 81        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
│ …       ┆ …    ┆ …        ┆ …     ┆ … ┆ …         ┆ …                   ┆ …   ┆ …          │
│ 19      ┆ 3    ┆ 00:14    ┆ P     ┆ … ┆ 14        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
│ 20      ┆ 3    ┆ 00:41    ┆       ┆ … ┆ 41        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
│ 21      ┆ 3    ┆ 00:44    ┆       ┆ … ┆ 44        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
│ 22      ┆ 3    ┆ 00:42    ┆       ┆ … ┆ 42        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
│ 23      ┆ null ┆ 01:13    ┆       ┆ … ┆ 73        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
└─────────┴──────┴──────────┴───────┴───┴───────────┴─────────────────────┴─────┴────────────┘

In [64]:
await scraper.scrape_team_rosters(teams=["MTL", "TOR"], seasons=[20242025], progress=False)

shape: (47, 20)
┌─────────┬─────────────┬───────────┬──────────┬───┬──────────┬────────────┬──────────┬────────────┐
│ id      ┆ headshot    ┆ firstName ┆ lastName ┆ … ┆ season   ┆ fullName   ┆ position ┆ meta_datet │
│ ---     ┆ ---         ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---        ┆ ---      ┆ ime        │
│ i64     ┆ str         ┆ str       ┆ str      ┆   ┆ i64      ┆ str        ┆ str      ┆ ---        │
│         ┆             ┆           ┆          ┆   ┆          ┆            ┆          ┆ datetime[μ │
│         ┆             ┆           ┆          ┆   ┆          ┆            ┆          ┆ s]         │
╞═════════╪═════════════╪═══════════╪══════════╪═══╪══════════╪════════════╪══════════╪════════════╡
│ 8476981 ┆ https://ass ┆ Josh      ┆ Anderson ┆ … ┆ 20242025 ┆ Josh       ┆ F        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Anderson   ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8476469 ┆ https://ass ┆ Joel      ┆ Armia    ┆ … ┆ 20242025 ┆ Joel Armia ┆ F        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆            ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8481540 ┆ https://ass ┆ Cole      ┆ Caufield ┆ … ┆ 20242025 ┆ Cole       ┆ F        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Caufield   ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8481523 ┆ https://ass ┆ Kirby     ┆ Dach     ┆ … ┆ 20242025 ┆ Kirby Dach ┆ F        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆            ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8477989 ┆ https://ass ┆ Christian ┆ Dvorak   ┆ … ┆ 20242025 ┆ Christian  ┆ F        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Dvorak     ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ …       ┆ …           ┆ …         ┆ …        ┆ … ┆ …        ┆ …          ┆ …        ┆ …          │
│ 8479026 ┆ https://ass ┆ Philippe  ┆ Myers    ┆ … ┆ 20242025 ┆ Philippe   ┆ D        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Myers      ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8476853 ┆ https://ass ┆ Morgan    ┆ Rielly   ┆ … ┆ 20242025 ┆ Morgan     ┆ D        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Rielly     ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8475690 ┆ https://ass ┆ Chris     ┆ Tanev    ┆ … ┆ 20242025 ┆ Chris      ┆ D        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Tanev      ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8476932 ┆ https://ass ┆ Anthony   ┆ Stolarz  ┆ … ┆ 20242025 ┆ Anthony    ┆ G        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Stolarz    ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8479361 ┆ https://ass ┆ Joseph    ┆ Woll     ┆ … ┆ 20242025 ┆ Joseph     ┆ G        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Woll       ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
└─────────┴─────────────┴───────────┴──────────┴───┴──────────┴────────────┴──────────┴────────────┘

In [69]:
await scraper.scrape_team_stats(teams=["MTL", "TOR"], seasons=[20242025], sessions=[2], progress=False)

shape: (55, 26)
┌──────────┬────────────┬───────────┬───────────┬───┬─────────┬────────────┬──────────┬────────────┐
│ playerId ┆ headshot   ┆ firstName ┆ lastName  ┆ … ┆ session ┆ fullName   ┆ position ┆ meta_datet │
│ ---      ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---     ┆ ---        ┆ ---      ┆ ime        │
│ i64      ┆ str        ┆ str       ┆ str       ┆   ┆ i64     ┆ str        ┆ str      ┆ ---        │
│          ┆            ┆           ┆           ┆   ┆         ┆            ┆          ┆ datetime[μ │
│          ┆            ┆           ┆           ┆   ┆         ┆            ┆          ┆ s]         │
╞══════════╪════════════╪═══════════╪═══════════╪═══╪═════════╪════════════╪══════════╪════════════╡
│ 8475233  ┆ https://as ┆ David     ┆ Savard    ┆ … ┆ 2       ┆ David      ┆ D        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Savard     ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8475848  ┆ https://as ┆ Brendan   ┆ Gallagher ┆ … ┆ 2       ┆ Brendan    ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Gallagher  ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8476469  ┆ https://as ┆ Joel      ┆ Armia     ┆ … ┆ 2       ┆ Joel Armia ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆            ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8476875  ┆ https://as ┆ Mike      ┆ Matheson  ┆ … ┆ 2       ┆ Mike       ┆ D        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Matheson   ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8476981  ┆ https://as ┆ Josh      ┆ Anderson  ┆ … ┆ 2       ┆ Josh       ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Anderson   ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ …        ┆ …          ┆ …         ┆ …         ┆ … ┆ …       ┆ …          ┆ …        ┆ …          │
│ 8481582  ┆ https://as ┆ Nicholas  ┆ Robertson ┆ … ┆ 2       ┆ Nicholas   ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Robertson  ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8482259  ┆ https://as ┆ Bobby     ┆ McMann    ┆ … ┆ 2       ┆ Bobby      ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ McMann     ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8482634  ┆ https://as ┆ Alex      ┆ Steeves   ┆ … ┆ 2       ┆ Alex       ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Steeves    ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8482720  ┆ https://as ┆ Matthew   ┆ Knies     ┆ … ┆ 2       ┆ Matthew    ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Knies      ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8484901  ┆ https://as ┆ Jacob     ┆ Quillan   ┆ … ┆ 2       ┆ Jacob      ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Quillan    ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
└──────────┴────────────┴───────────┴───────────┴───┴─────────┴────────────┴──────────┴────────────┘

In [70]:
await scraper.scrape_standings(date="2025-03-10")

Scraping NHL Standings:   0%|          | 0/1 [00:00<?, ?it/s]

Scraping NHL Standings: 100%|██████████| 1/1 [00:00<00:00,  2.46it/s]

shape: (32, 83)
┌────────────┬────────────┬────────────┬────────────┬───┬──────┬───────────┬───────────┬───────────┐
│ conference ┆ conference ┆ conference ┆ conference ┆ … ┆ wins ┆ abbreviat ┆ division  ┆ conferenc │
│ Abbrev     ┆ HomeSequen ┆ L10Sequenc ┆ Name       ┆   ┆ ---  ┆ ion       ┆ ---       ┆ e         │
│ ---        ┆ ce         ┆ e          ┆ ---        ┆   ┆ i32  ┆ ---       ┆ str       ┆ ---       │
│ str        ┆ ---        ┆ ---        ┆ str        ┆   ┆      ┆ str       ┆           ┆ str       │
│            ┆ i64        ┆ i64        ┆            ┆   ┆      ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪══════╪═══════════╪═══════════╪═══════════╡
│ E          ┆ 3          ┆ 3          ┆ Eastern    ┆ … ┆ 42   ┆ WSH       ┆ Metropoli ┆ Eastern   │
│            ┆            ┆            ┆            ┆   ┆      ┆           ┆ tan       ┆           │
│ W          ┆ 2          ┆ 5          ┆ Western    ┆ … ┆ 44   ┆ WPG       ┆ Central   ┆ Western   │
│ W          ┆ 3          ┆ 2          ┆ Western    ┆ … ┆ 42   ┆ DAL       ┆ Central   ┆ Western   │
│ E          ┆ 4          ┆ 2          ┆ Eastern    ┆ … ┆ 40   ┆ FLA       ┆ Atlantic  ┆ Eastern   │
│ W          ┆ 1          ┆ 4          ┆ Western    ┆ … ┆ 38   ┆ VGK       ┆ Pacific   ┆ Western   │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …    ┆ …         ┆ …         ┆ …         │
│ W          ┆ 12         ┆ 13         ┆ Western    ┆ … ┆ 27   ┆ SEA       ┆ Pacific   ┆ Western   │
│ E          ┆ 11         ┆ 13         ┆ Eastern    ┆ … ┆ 25   ┆ BUF       ┆ Atlantic  ┆ Eastern   │
│ W          ┆ 8          ┆ 6          ┆ Western    ┆ … ┆ 24   ┆ NSH       ┆ Central   ┆ Western   │
│ W          ┆ 14         ┆ 14         ┆ Western    ┆ … ┆ 20   ┆ CHI       ┆ Central   ┆ Western   │
│ W          ┆ 16         ┆ 15         ┆ Western    ┆ … ┆ 17   ┆ SJS       ┆ Pacific   ┆ Western   │
└────────────┴────────────┴────────────┴────────────┴───┴──────┴───────────┴───────────┴───────────┘

In [71]:
await scraper.scrape_draft(years=[i for i in range(2010, 2025)])

Scraping NHL Draft Data:   0%|          | 0/15 [00:00<?, ?it/s]

Scraping NHL Draft Data: 100%|██████████| 15/15 [00:00<00:00, 48.80it/s]

shape: (3_235, 23)
┌───────┬─────────────┬────────────┬────────┬───┬────────────┬───────────┬────────────┬────────────┐
│ round ┆ pickInRound ┆ overallPic ┆ teamId ┆ … ┆ amateurClu ┆ draftYear ┆ fullName   ┆ meta_datet │
│ ---   ┆ ---         ┆ k          ┆ ---    ┆   ┆ bName      ┆ ---       ┆ ---        ┆ ime        │
│ i64   ┆ i64         ┆ ---        ┆ i64    ┆   ┆ ---        ┆ i64       ┆ str        ┆ ---        │
│       ┆             ┆ i64        ┆        ┆   ┆ str        ┆           ┆            ┆ datetime[μ │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ s]         │
╞═══════╪═════════════╪════════════╪════════╪═══╪════════════╪═══════════╪════════════╪════════════╡
│ 1     ┆ 1           ┆ 1          ┆ 16     ┆ … ┆ Regina     ┆ 2023      ┆ Connor     ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Bedard     ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 1     ┆ 2           ┆ 2          ┆ 24     ┆ … ┆ Orebro     ┆ 2023      ┆ Leo        ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Carlsson   ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 1     ┆ 3           ┆ 3          ┆ 29     ┆ … ┆ Michigan   ┆ 2023      ┆ Adam       ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Fantilli   ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 1     ┆ 4           ┆ 4          ┆ 28     ┆ … ┆ USA U-18   ┆ 2023      ┆ Will Smith ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 1     ┆ 5           ┆ 5          ┆ 8      ┆ … ┆ Kloten     ┆ 2023      ┆ David      ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Reinbacher ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ …     ┆ …           ┆ …          ┆ …      ┆ … ┆ …          ┆ …         ┆ …          ┆ …          │
│ 7     ┆ 27          ┆ 213        ┆ 18     ┆ … ┆ Pardubice  ┆ 2018      ┆ Milan      ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Kloucek    ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 7     ┆ 28          ┆ 214        ┆ 14     ┆ … ┆ Vernon     ┆ 2018      ┆ Ty Taylor  ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 7     ┆ 29          ┆ 215        ┆ 52     ┆ … ┆ Okotoks    ┆ 2018      ┆ Austin     ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Wong       ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 7     ┆ 30          ┆ 216        ┆ 3      ┆ … ┆ St. Sebast ┆ 2018      ┆ Riley      ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆ ian's      ┆           ┆ Hughes     ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆ School     ┆           ┆            ┆ 02382      │
│ 7     ┆ 31          ┆ 217        ┆ 15     ┆ … ┆ Saskatoon  ┆ 2018      ┆ Eric       ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Florchuk   ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
└───────┴─────────────┴────────────┴────────┴───┴────────────┴───────────┴────────────┴────────────┘

In [62]:
df = await scraper.scrape_team_schedule(team="MTL", season=20242025)

df

Scraping NHL Team Schedule: 100%|██████████| 1/1 [00:01<00:00,  1.44s/it]

shape: (88, 36)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ season   ┆ gameType ┆ gameDate  ┆ … ┆ winningGo ┆ winningGo ┆ winningGo ┆ meta_date │
│ ---        ┆ ---      ┆ ---      ┆ ---       ┆   ┆ alScorerI ┆ alScorerF ┆ alScorerL ┆ time      │
│ i64        ┆ i64      ┆ i64      ┆ date      ┆   ┆ d         ┆ irstIniti ┆ astName   ┆ ---       │
│            ┆          ┆          ┆           ┆   ┆ ---       ┆ al        ┆ ---       ┆ datetime[ │
│            ┆          ┆          ┆           ┆   ┆ i64       ┆ ---       ┆ str       ┆ μs]       │
│            ┆          ┆          ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2024010015 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ 8482134   ┆ L.        ┆ Tuch      ┆ 2025-03-2 │
│            ┆          ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024010022 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ 8479543   ┆ M.        ┆ Pezzetta  ┆ 2025-03-2 │
│            ┆          ┆          ┆ 4         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024010038 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ 8481582   ┆ N.        ┆ Robertson ┆ 2025-03-2 │
│            ┆          ┆          ┆ 6         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024010055 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ 8481582   ┆ N.        ┆ Robertson ┆ 2025-03-2 │
│            ┆          ┆          ┆ 8         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024010073 ┆ 20242025 ┆ 1        ┆ 2024-10-0 ┆ … ┆ 8484759   ┆ C.        ┆ Yakemchuk ┆ 2025-03-2 │
│            ┆          ┆          ┆ 1         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ …          ┆ …        ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024021236 ┆ 20242025 ┆ 2        ┆ 2025-04-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-03-2 │
│            ┆          ┆          ┆ 8         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024021260 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-03-2 │
│            ┆          ┆          ┆ 1         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024021269 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-03-2 │
│            ┆          ┆          ┆ 2         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024021285 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-03-2 │
│            ┆          ┆          ┆ 4         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024021301 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-03-2 │
│            ┆          ┆          ┆ 6         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [82]:
await scraper.scrape_schedule(teams=["MTL", "TOR"], seasons=[20242025])

Scraping NHL Schedule: 100%|██████████| 2/2 [00:00<00:00,  3.73it/s]

shape: (176, 37)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ season   ┆ gameType ┆ gameDate  ┆ … ┆ winningGo ┆ winningGo ┆ _gameType ┆ meta_date │
│ ---        ┆ ---      ┆ ---      ┆ ---       ┆   ┆ alScorerF ┆ alScorerL ┆ ---       ┆ time      │
│ i64        ┆ i64      ┆ i64      ┆ date      ┆   ┆ irstIniti ┆ astName   ┆ str       ┆ ---       │
│            ┆          ┆          ┆           ┆   ┆ al        ┆ ---       ┆           ┆ datetime[ │
│            ┆          ┆          ┆           ┆   ┆ ---       ┆ str       ┆           ┆ μs]       │
│            ┆          ┆          ┆           ┆   ┆ str       ┆           ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2024010015 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ L.        ┆ Tuch      ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024010022 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ M.        ┆ Pezzetta  ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 4         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024010038 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ N.        ┆ Robertson ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 6         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024010055 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ N.        ┆ Robertson ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 8         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024010073 ┆ 20242025 ┆ 1        ┆ 2024-10-0 ┆ … ┆ C.        ┆ Yakemchuk ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 1         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ …          ┆ …        ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024021245 ┆ 20242025 ┆ 2        ┆ 2025-04-0 ┆ … ┆ null      ┆ null      ┆ regular   ┆ 2025-03-2 │
│            ┆          ┆          ┆ 9         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024021269 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ regular   ┆ 2025-03-2 │
│            ┆          ┆          ┆ 2         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024021279 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ regular   ┆ 2025-03-2 │
│            ┆          ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024021292 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ regular   ┆ 2025-03-2 │
│            ┆          ┆          ┆ 5         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024021308 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ regular   ┆ 2025-03-2 │
│            ┆          ┆          ┆ 7         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [118]:
scraper = scraper.Scraper()
df = await scraper.scrape_teams("active")

df.select(["abbrev"])

Scraping NHL Teams: 100%|██████████| 1/1 [00:00<00:00,  2.76it/s]

shape: (32, 1)
┌────────┐
│ abbrev │
│ ---    │
│ str    │
╞════════╡
│ NJD    │
│ NYI    │
│ NYR    │
│ PHI    │
│ PIT    │
│ …      │
│ MIN    │
│ WPG    │
│ VGK    │
│ SEA    │
│ UTA    │
└────────┘